alter table THESISSUMMER_PROTOCOL_KK add constraint FK_THESISSUMMER_PROTOCOL_KK_ON_TYPE_PROTOCOL foreign key (TYPE_PROTOCOL_ID) references THESISSUMMER_TYPE_PROTOCOL_KK(ID);
alter table THESISSUMMER_PROTOCOL_KK add constraint FK_THESISSUMMER_PROTOCOL_KK_ON_CITY foreign key (CITY_ID) references THESISSUMMER_CITY(ID);
alter table THESISSUMMER_PROTOCOL_KK add constraint FK_THESISSUMMER_PROTOCOL_KK_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE;
create index IDX_THESISSUMMER_PROTOCOL_KK_ON_TYPE_PROTOCOL on THESISSUMMER_PROTOCOL_KK (TYPE_PROTOCOL_ID);
create index IDX_THESISSUMMER_PROTOCOL_KK_ON_CITY on THESISSUMMER_PROTOCOL_KK (CITY_ID);
