-- begin THESISSUMMER_ORDER_DOCUMENT
alter table THESISSUMMER_ORDER_DOCUMENT add constraint FK_THESISSUMMER_ORDER_DOCUMENT_ON_SET_ORDER foreign key (SET_ORDER_ID) references SYS_FILE(ID)^
alter table THESISSUMMER_ORDER_DOCUMENT add constraint FK_THESISSUMMER_ORDER_DOCUMENT_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
create index IDX_THESISSUMMER_ORDER_DOCUMENT_ON_SET_ORDER on THESISSUMMER_ORDER_DOCUMENT (SET_ORDER_ID)^
-- end THESISSUMMER_ORDER_DOCUMENT
-- begin THESISSUMMER_MEMO
alter table THESISSUMMER_MEMO add constraint FK_THESISSUMMER_MEMO_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_MEMO
-- begin THESISSUMMER_ORDER_DOCUMENT1C
alter table THESISSUMMER_ORDER_DOCUMENT1C add constraint FK_THESISSUMMER_ORDER_DOCUMENT1C_ON_ORDER_DOCUMENT foreign key (ORDER_DOCUMENT_ID) references THESISSUMMER_ORDER_DOCUMENT(CARD_ID)^
create index IDX_THESISSUMMER_ORDER_DOCUMENT1C_ON_ORDER_DOCUMENT on THESISSUMMER_ORDER_DOCUMENT1C (ORDER_DOCUMENT_ID)^
-- end THESISSUMMER_ORDER_DOCUMENT1C
-- begin THESISSUMMER_ORDER_DOCUMENT_FULL1C
alter table THESISSUMMER_ORDER_DOCUMENT_FULL1C add constraint FK_THESISSUMMER_ORDER_DOCUMENT_FULL1C_ON_ORDER_DOCUMENT foreign key (ORDER_DOCUMENT_ID) references THESISSUMMER_ORDER_DOCUMENT(CARD_ID)^
alter table THESISSUMMER_ORDER_DOCUMENT_FULL1C add constraint FK_THESISSUMMER_ORDER_DOCUMENT_FULL1C_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
create index IDX_THESISSUMMER_ORDER_DOCUMENT_FULL1C_ON_ORDER_DOCUMENT on THESISSUMMER_ORDER_DOCUMENT_FULL1C (ORDER_DOCUMENT_ID)^
-- end THESISSUMMER_ORDER_DOCUMENT_FULL1C
-- begin THESISSUMMER_PROTOCOL_FILE_TEMPLATE
alter table THESISSUMMER_PROTOCOL_FILE_TEMPLATE add constraint FK_THESISSUMMER_PROTOCOL_FILE_TEMPLATE_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
create index IDX_THESISSUMMER_PROTOCOL_FILE_TEMPLATE_ON_FILE_DESCRIPTOR on THESISSUMMER_PROTOCOL_FILE_TEMPLATE (FILE_DESCRIPTOR_ID)^
-- end THESISSUMMER_PROTOCOL_FILE_TEMPLATE
