-- begin THESISSUMMER_ORDER_LOAN
alter table THESISSUMMER_ORDER_LOAN add constraint FK_THESISSUMMER_ORDER_LOAN_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_LOAN
-- begin THESISSUMMER_ORDER_INS
alter table THESISSUMMER_ORDER_INS add constraint FK_THESISSUMMER_ORDER_INS_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_INS
-- begin THESISSUMMER_ORDER_TRANFER_MONEY
alter table THESISSUMMER_ORDER_TRANFER_MONEY add constraint FK_THESISSUMMER_ORDER_TRANFER_MONEY_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_TRANFER_MONEY
-- begin THESISSUMMER_ORDER_LOAN_SI
alter table THESISSUMMER_ORDER_LOAN_SI add constraint FK_THESISSUMMER_ORDER_LOAN_SI_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_LOAN_SI
-- begin THESISSUMMER_ORDER_VOZVRATV_GU
alter table THESISSUMMER_ORDER_VOZVRATV_GU add constraint FK_THESISSUMMER_ORDER_VOZVRATV_GU_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_VOZVRATV_GU
