-- begin THESISSUMMER_ORDER_LOAN
alter table THESISSUMMER_ORDER_LOAN add constraint FK_THESISSUMMER_ORDER_LOAN_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_LOAN
-- begin THESISSUMMER_ORDER_INS
alter table THESISSUMMER_ORDER_INS add constraint FK_THESISSUMMER_ORDER_INS_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_INS
-- begin THESISSUMMER_ORDER_TRANFER_MONEY
alter table THESISSUMMER_ORDER_TRANFER_MONEY add constraint FK_THESISSUMMER_ORDER_TRANFER_MONEY_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_TRANFER_MONEY
-- begin THESISSUMMER_ORDER_LOAN_SI
alter table THESISSUMMER_ORDER_LOAN_SI add constraint FK_THESISSUMMER_ORDER_LOAN_SI_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_LOAN_SI
-- begin THESISSUMMER_ORDER_VOZVRATV_GU
alter table THESISSUMMER_ORDER_VOZVRATV_GU add constraint FK_THESISSUMMER_ORDER_VOZVRATV_GU_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_VOZVRATV_GU
-- begin THESISSUMMER_ORDER_RETURN_NEISP_SUB1C
alter table THESISSUMMER_ORDER_RETURN_NEISP_SUB1C add constraint FK_THESISSUMMER_ORDERETUNEISSUB1_ON_ORDER_RETURN_NEISP_SUB foreign key (ORDER_RETURN_NEISP_SUB_ID) references THESISSUMMER_ORDER_RETURN_NEISP_SUB(CARD_ID)^
create index IDX_THESISSUMMER_ORDERETUNEISSUB1_ON_ORDER_RETURN_NEISP_SUB on THESISSUMMER_ORDER_RETURN_NEISP_SUB1C (ORDER_RETURN_NEISP_SUB_ID)^
-- end THESISSUMMER_ORDER_RETURN_NEISP_SUB1C
-- begin THESISSUMMER_ORDER_RETURN_NEISP_SUB
alter table THESISSUMMER_ORDER_RETURN_NEISP_SUB add constraint FK_THESISSUMMER_ORDER_RETURN_NEISP_SUB_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_RETURN_NEISP_SUB
-- begin THESISSUMMER_ORDER_REMBURSEMENT1C
alter table THESISSUMMER_ORDER_REMBURSEMENT1C add constraint FK_THESISSUMMER_ORDER_REMBURSEMENT1C_ON_ORDER_REMBURSEMENT foreign key (ORDER_REMBURSEMENT_ID) references THESISSUMMER_ORDER_REMBURSEMENT(CARD_ID)^
create index IDX_THESISSUMMER_ORDER_REMBURSEMENT1C_ON_ORDER_REMBURSEMENT on THESISSUMMER_ORDER_REMBURSEMENT1C (ORDER_REMBURSEMENT_ID)^
-- end THESISSUMMER_ORDER_REMBURSEMENT1C
-- begin THESISSUMMER_ORDER_REMBURSEMENT
alter table THESISSUMMER_ORDER_REMBURSEMENT add constraint FK_THESISSUMMER_ORDER_REMBURSEMENT_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_REMBURSEMENT
-- begin THESISSUMMER_ORDER_POSTING1C
alter table THESISSUMMER_ORDER_POSTING1C add constraint FK_THESISSUMMER_ORDER_POSTING1C_ON_ORDER_POSTING foreign key (ORDER_POSTING_ID) references THESISSUMMER_ORDER_POSTING(CARD_ID)^
create index IDX_THESISSUMMER_ORDER_POSTING1C_ON_ORDER_POSTING on THESISSUMMER_ORDER_POSTING1C (ORDER_POSTING_ID)^
-- end THESISSUMMER_ORDER_POSTING1C
-- begin THESISSUMMER_ORDER_POSTING
alter table THESISSUMMER_ORDER_POSTING add constraint FK_THESISSUMMER_ORDER_POSTING_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_POSTING
-- begin THESISSUMMER_ORDER_REVALUATION1C
alter table THESISSUMMER_ORDER_REVALUATION1C add constraint FK_THESISSUMMER_ORDER_REVALUATION1C_ON_ORDER_REVALUATION foreign key (ORDER_REVALUATION_ID) references THESISSUMMER_ORDER_REVALUATION(CARD_ID)^
create index IDX_THESISSUMMER_ORDER_REVALUATION1C_ON_ORDER_REVALUATION on THESISSUMMER_ORDER_REVALUATION1C (ORDER_REVALUATION_ID)^
-- end THESISSUMMER_ORDER_REVALUATION1C
-- begin THESISSUMMER_ORDER_REVALUATION
alter table THESISSUMMER_ORDER_REVALUATION add constraint FK_THESISSUMMER_ORDER_REVALUATION_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_REVALUATION
-- begin THESISSUMMER_ORDER_TRANFER1C
alter table THESISSUMMER_ORDER_TRANFER1C add constraint FK_THESISSUMMER_ORDER_TRANFER1C_ON_ORDER_TRANFER foreign key (ORDER_TRANFER_ID) references THESISSUMMER_ORDER_TRANFER(CARD_ID)^
create index IDX_THESISSUMMER_ORDER_TRANFER1C_ON_ORDER_TRANFER on THESISSUMMER_ORDER_TRANFER1C (ORDER_TRANFER_ID)^
-- end THESISSUMMER_ORDER_TRANFER1C
-- begin THESISSUMMER_ORDER_TRANFER
alter table THESISSUMMER_ORDER_TRANFER add constraint FK_THESISSUMMER_ORDER_TRANFER_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_TRANFER
-- begin THESISSUMMER_ORDER_WRITE_OFF1C
alter table THESISSUMMER_ORDER_WRITE_OFF1C add constraint FK_THESISSUMMER_ORDER_WRITE_OFF1C_ON_ORDER_WRITE_OFF foreign key (ORDER_WRITE_OFF_ID) references THESISSUMMER_ORDER_WRITE_OFF(CARD_ID)^
create index IDX_THESISSUMMER_ORDER_WRITE_OFF1C_ON_ORDER_WRITE_OFF on THESISSUMMER_ORDER_WRITE_OFF1C (ORDER_WRITE_OFF_ID)^
-- end THESISSUMMER_ORDER_WRITE_OFF1C
-- begin THESISSUMMER_ORDER_WRITE_OFF
alter table THESISSUMMER_ORDER_WRITE_OFF add constraint FK_THESISSUMMER_ORDER_WRITE_OFF_ON_CARD foreign key (CARD_ID) references WF_CARD(ID) on delete CASCADE^
-- end THESISSUMMER_ORDER_WRITE_OFF
