alter table thesissummer_order_document1c drop constraint FK_THESISSUMMER_ORDER_DOCUMENT1C_ON_ORDER_DOCUMENT ;
alter table thesissummer_order_document_full1c drop constraint FK_THESISSUMMER_ORDER_DOCUMENT_FULL1C_ON_ORDER_DOCUMENT ;
